import { defineStore } from 'pinia';
// Import classes from the JavaScript version of components.js
// Note: We don't need to import them if we are only using their properties
// and assuming the structure passed around is correct.
// For actions like addChildToComponent, etc., the structure is implicitly expected.
// import { FormComponent, TableComponent, SelectComponent } from '../core/components.js';

export const useCanvasStore = defineStore('canvas', {
  state: () => ({
    components: [], // This will hold instances of components from core/components.js
  }),
  getters: {
    getComponentById: (state) => (id) => {
      return state.components.find(component => component.id === id);
    },
    // allComponents: (state) => state.components,
  },
  actions: {
    addComponent(component) {
      if (!component.id) {
        console.error('Component added without an ID:', component);
        // ID should be generated by the component constructor itself
      }
      // Set order before pushing
      component.order = this.components.length;
      this.components.push(component);
    },
    // updateComponentPosition action is removed as per instructions.

    setComponents(newComponentsArray) {
      // It's assumed newComponentsArray is an array of component objects
      // that are compatible with what the application expects.
      // If re-ordering is also needed, it should be handled here or before calling.
      this.components = newComponentsArray;
    },

    addChildToComponent({ parentId, childComponent }) {
      const parentComponent = this.getComponentById(parentId); // Using getter
      if (parentComponent && parentComponent.type === 'Form') {
        if (!parentComponent.children) {
           parentComponent.children = [];
        }
        if (!childComponent || !childComponent.id) {
          console.error('Child component added without an ID or is invalid:', childComponent);
          return;
        }
        parentComponent.children.push(childComponent);
        console.log(`Child component ${childComponent.id} added to parent ${parentId}`);
      } else {
        console.warn(`FormComponent with ID ${parentId} not found or is not a FormComponent.`);
      }
    },
    updateTableConfiguration({ componentId, rows, cols, headers }) {
      const table = this.getComponentById(componentId);
      if (table && table.type === 'Table') {
        const numRows = parseInt(rows, 10);
        const numCols = parseInt(cols, 10);

        if (isNaN(numRows) || numRows <= 0) {
          console.warn(`Invalid number of rows: ${rows}. Must be a positive integer.`);
          return;
        }
        if (isNaN(numCols) || numCols <= 0) {
          console.warn(`Invalid number of columns: ${cols}. Must be a positive integer.`);
          return;
        }

        table.rows = numRows;
        table.cols = numCols;

        const parsedHeaders = headers.split(',').map(h => h.trim()).filter(h => h);
        if (parsedHeaders.length !== numCols) {
          table.headers = Array.from({ length: numCols }, (_, i) => `Header ${i + 1}`);
          console.warn(`Header count mismatch for Table ${componentId}. Expected ${numCols}, got ${parsedHeaders.length}. Generating default headers.`);
        } else {
          table.headers = parsedHeaders;
        }

        table.cells = Array(table.rows).fill(null).map(() => Array(table.cols).fill(null));

        console.log(`Table ${componentId} configuration updated: ${numRows}x${numCols}, Headers:`, table.headers);
      } else {
        console.warn(`TableComponent with ID ${componentId} not found or is not a TableComponent.`);
      }
    },
    updateSelectOptions({ componentId, newOptions }) {
      const selectComp = this.getComponentById(componentId);
      if (selectComp && selectComp.type === 'Select') {
        // Basic validation for JavaScript
        if (Array.isArray(newOptions) && newOptions.every(opt => typeof opt.value === 'string' && typeof opt.text === 'string')) {
          selectComp.options = newOptions;
          console.log(`Select component ${componentId} options updated:`, newOptions);
        } else {
          console.error(`Invalid newOptions format for Select ${componentId}. Expected array of {value: string, text: string}.`, newOptions);
        }
      } else {
        console.warn(`SelectComponent with ID ${componentId} not found or is not a SelectComponent.`);
      }
    },
    addComponentToTableCell({ tableId, rowIndex, colIndex, childComponent }) {
      const tableComponent = this.getComponentById(tableId);
      if (tableComponent && tableComponent.type === 'Table') {
        if (!childComponent || !childComponent.id) {
          console.error('Invalid child FormComponent or child component without ID for table cell.');
          return;
        }
        if (tableComponent.cells && tableComponent.cells[rowIndex] && typeof tableComponent.cells[rowIndex][colIndex] !== 'undefined') {
          if (tableComponent.cells[rowIndex][colIndex] === null) {
            tableComponent.cells[rowIndex][colIndex] = childComponent;
            console.log(`FormComponent ${childComponent.id} added to Table ${tableId} at cell [${rowIndex}][${colIndex}]`);
          } else {
            const existingId = tableComponent.cells[rowIndex][colIndex].id;
            console.warn(`Cell [${rowIndex}][${colIndex}] in Table ${tableId} is already occupied by component ${existingId}.`);
          }
        } else {
          console.error(`Cell [${rowIndex}][${colIndex}] is not accessible in Table ${tableId}.`);
        }
      } else {
        console.warn(`TableComponent with ID ${tableId} not found or is not a TableComponent.`);
      }
    },
    // removeComponent(id) {
    //   this.components = this.components.filter(comp => comp.id !== id);
    // }
  },
});
